# fly.toml app configuration file for roblox-inklet-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roblox-inklet-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # <-- CORREÇÃO 1: Não desligar a máquina
  auto_start_machines = true # <-- Deixar true para garantir que ela ligue se parar por algum motivo
  min_machines_running = 1    # <-- CORREÇÃO 2: Manter no mínimo 1 máquina sempre ligada
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256             # <-- CORREÇÃO 3: Definir a memória para a cota gratuita